name: E2E Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    
    # コミットメッセージに[skip e2e]が含まれている場合はスキップ
    if: ${{ !contains(github.event.head_commit.message, '[skip e2e]') }}
    
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: trends_laravel_e2e
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4
      
      - name: Node.jsセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: PHPセットアップ
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql, pdo_mysql
          tools: composer:v2
      
      - name: Playwrightブラウザインストール
        run: npx playwright install --with-deps chromium
      
      - name: PHP依存関係をインストール
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      
      - name: Node.js依存関係をインストール
        run: npm ci
      
      - name: 環境ファイルを作成
        run: |
          cp .env.ci .env
          php artisan key:generate
      
      - name: フロントエンドアセットをビルド
        run: npm run build
      
      - name: データベースを設定
        run: |
          php artisan config:cache
          php artisan migrate:fresh --force
          php artisan db:seed --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: trends_laravel_e2e
          DB_USERNAME: root
          DB_PASSWORD: password
      
      - name: Laravel開発サーバーを起動
        run: |
          php artisan serve --host=0.0.0.0 --port=8000 &
          sleep 10
          curl -f http://localhost:8000 || (echo "Laravel server failed to start" && exit 1)
        env:
          APP_URL: http://localhost:8000
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: trends_laravel_e2e
          DB_USERNAME: root
          DB_PASSWORD: password
      
      - name: E2Eテストを実行
        run: npx playwright test --workers=4
        env:
          APP_URL: http://localhost:8000
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: trends_laravel_e2e
          DB_USERNAME: root
          DB_PASSWORD: password
      
      - name: Playwrightレポートをアップロード
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30