name: E2E Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    container: kirschbaumdevelopment/laravel-test-runner:8.2
    
    # コミットメッセージに[skip e2e]が含まれている場合はスキップ
    if: ${{ !contains(github.event.head_commit.message, '[skip e2e]') }}
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: trends_laravel_e2e
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4
      
      - name: Node.js 20をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: PostgreSQL PHP拡張をインストール
        run: |
          apt-get update
          apt-get install -y libpq-dev
          docker-php-ext-install pgsql pdo_pgsql
      
      - name: Playwrightブラウザインストール
        run: npx playwright install --with-deps chromium
      
      - name: Composer依存関係をキャッシュ
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-v2-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-v2-
      
      - name: PHP依存関係をインストール
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      
      - name: Node.js依存関係をインストール
        run: npm ci
      
      - name: 環境ファイルを作成
        run: |
          cp .env.ci .env
          php artisan key:generate
      
      - name: フロントエンドアセットをビルド
        run: npm run build
      
      - name: データベースを設定
        run: |
          php artisan config:cache
          php artisan migrate:fresh --force
          php artisan db:seed --force
        env:
          DB_CONNECTION: pgsql
          DB_HOST: postgres
          DB_PORT: 5432
          DB_DATABASE: trends_laravel_e2e
          DB_USERNAME: postgres
          DB_PASSWORD: password
      
      - name: Laravel開発サーバーを起動
        run: |
          php artisan serve --host=0.0.0.0 --port=8000 &
          sleep 10
          curl -f http://localhost:8000 || (echo "Laravel server failed to start" && exit 1)
        env:
          APP_URL: http://localhost:8000
          DB_CONNECTION: pgsql
          DB_HOST: postgres
          DB_PORT: 5432
          DB_DATABASE: trends_laravel_e2e
          DB_USERNAME: postgres
          DB_PASSWORD: password
      
      - name: E2Eテストを実行
        run: npx playwright test --workers=4
        env:
          APP_URL: http://localhost:8000
          DB_CONNECTION: pgsql
          DB_HOST: postgres
          DB_PORT: 5432
          DB_DATABASE: trends_laravel_e2e
          DB_USERNAME: postgres
          DB_PASSWORD: password
      
      - name: Playwrightレポートをアップロード
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30