name: Wiki同期

on:
  push:
    branches: [main]
    paths:
      - 'docs/wiki/**'
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Wikiに同期
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/wiki/
          token: ${{ secrets.GITHUB_TOKEN }}